# Generated by Django 5.0 on 2024-06-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm_settings', '0001_initial'),
        ('leave', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveallocationtwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedleave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveallocationone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidaytwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='employee_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.grade'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidayone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveallocationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveallocationrequesttwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveallocationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveallocationrequestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applicable_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ethnicgroup'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicytwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveallocationrequest',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='approvedleave',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassignthree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassigntwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavepolicyassignone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaverequesttwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaverequestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.fiscalyear'),
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('title', 'date'), name='Holiday_title_date'),
        ),
        migrations.AddConstraint(
            model_name='approvedleave',
            constraint=models.UniqueConstraint(fields=('leavepolicy', 'user', 'date'), name='Leaveallocation_leavepolicy_user_date'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyassign',
            constraint=models.UniqueConstraint(fields=('user', 'leavepolicy'), name='Leavepolicyassign_user_leavepolicy'),
        ),
        migrations.AddConstraint(
            model_name='leavesummary',
            constraint=models.UniqueConstraint(fields=('user', 'leavepolicy'), name='Leavesummary_user_leavepolicy'),
        ),
    ]
