# Generated by Django 5.0 on 2024-05-22 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaveallocation',
            new_name='Approvedleave',
        ),
    ]
