# Generated by Django 5.0 on 2024-07-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0001_initial'),
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesummary',
            name='general_settings',
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_settings.fiscalyear'),
        ),
    ]
