# Generated by Django 5.0 on 2024-08-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='extended_days',
        ),
    ]
