# Generated by Django 5.0 on 2024-06-30 09:49

import leave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leavepolicy_applicable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveallocationrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=leave.models.uploadfileallocationrequest),
        ),
    ]
