# Generated by Django 5.0 on 2024-07-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0001_initial'),
        ('leave', '0003_remove_leavesummary_general_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesummary',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.fiscalyear'),
        ),
    ]
