# Generated by Django 5.0 on 2024-08-22 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leaverequest_extended_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicyassign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassign_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavepolicyassign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassign_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavepolicyassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavepolicyassign_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
