# Generated by Django 5.0 on 2024-07-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveallocationrequest_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesummary',
            name='fiscal_year',
        ),
    ]
