# Generated by Django 5.0 on 2024-05-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveallocationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidaytwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidayone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicytwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassignthree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicyassign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leavepolicyassigntwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavepolicyassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavepolicyassignone', to=settings.AUTH_USER_MODEL),
        ),
    ]
