# Generated by Django 5.0 on 2024-08-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0001_initial'),
        ('leave', '0004_alter_leavepolicyassign_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesummary',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavesummary_fiscal_year', to='hrm_settings.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='leavesummary',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavesummary_leavepolicy', to='leave.leavepolicy'),
        ),
        migrations.AlterField(
            model_name='leavesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavesummary_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
