# Generated by Django 5.0 on 2024-05-22 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_holiday_created_by_holiday_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveallocationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveallocationrequesttwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveallocationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveallocationrequestone', to=settings.AUTH_USER_MODEL),
        ),
    ]
