# Generated by Django 5.0 on 2024-07-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leaveallocationrequest_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='exchange_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_with_leaverequest', to='leave.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('Regular Leave', 'Regular Leave'), ('Extend Existing', 'Extend Existing'), ('New Allocation', 'New Allocation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leavepolicy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavepolicy_leaverequest', to='leave.leavepolicy'),
        ),
    ]
