# Generated by Django 5.0 on 2024-07-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0021_generalsettings_delete_consecutivelateattendance_and_more'),
        ('leave', '0005_remove_leavesummary_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesummary',
            name='general_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.generalsettings'),
        ),
    ]
