# Generated by Django 5.0 on 2024-07-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0022_alter_generalsettings_fiscalyear_month'),
        ('leave', '0006_leavesummary_general_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesummary',
            name='general_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.generalsettings'),
        ),
    ]
