# Generated by Django 5.0 on 2024-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaverequest_exchange_with_leaverequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('Regular Leave', 'Regular Leave'), ('Extend Existing', 'Extend Existing'), ('New Allocation', 'New Allocation')], max_length=20),
        ),
    ]
