# Generated by Django 5.0 on 2024-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leaverequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='extended_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
