# Generated by Django 5.0 on 2024-07-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leaverequest_extended_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='rejection_reason',
            new_name='reason',
        ),
    ]
