# Generated by Django 5.0 on 2024-07-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_alter_leaverequest_from_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaveallocationrequest',
        ),
    ]
