# Generated by Django 5.0 on 2024-09-05 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='hours_to_consider_absent',
            field=models.FloatField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='hours_to_consider_half_Day',
            field=models.FloatField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='overtime_salary_on_holiday',
            field=models.FloatField(default=200, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='overtime_salary_on_workingday',
            field=models.FloatField(default=150, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='shift_exceeded_time_to_considered_overtime',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
