# Generated by Django 5.0 on 2024-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('from_month', 'to_month'), name='Fiscalyear_from_month_to_month'),
        ),
    ]
