# Generated by Django 5.0 on 2024-07-15 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0002_fiscalyear_fiscalyear_from_month_to_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='basic_salary_percentage',
            field=models.FloatField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
