# Generated by Django 5.0 on 2024-07-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0002_fiscalyear_from_month_fiscalyear_to_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='from_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='to_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20, null=True),
        ),
    ]
