# Generated by Django 5.0 on 2024-07-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0004_alter_fiscalyear_from_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalyear',
            old_name='from_month',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='to_month',
        ),
    ]
