# Generated by Django 5.0 on 2024-07-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0006_alter_fiscalyear_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='to_date',
        ),
    ]
