# Generated by Django 5.0 on 2024-07-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_office_off_day'),
        ('hrm_settings', '0009_holiday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holiday',
            new_name='Weeklyholiday',
        ),
    ]
