# Generated by Django 5.0 on 2024-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0010_rename_holiday_weeklyholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyholiday',
            name='day',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True, unique=True),
        ),
    ]
