# Generated by Django 5.0 on 2024-07-02 08:32

import django.contrib.postgres.fields
import django.core.validators
import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0011_alter_weeklyholiday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fiscalyear_month', models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='January', max_length=20)),
                ('working_day', models.TimeField()),
                ('holidays_as_working_days', models.BooleanField(default=False)),
                ('consecutive_late_attendance_fine', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('consecutive_late_attendance_fine_percentage', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('halfday_salary_percentage', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_working_hours', models.FloatField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('consider_attendance_on_holidays', models.CharField(choices=[('Disabled', 'Disabled'), ('Overtime', 'Overtime')], default='Overtime', max_length=15)),
                ('allow_overtime', models.BooleanField(default=True)),
                ('weekly_holidays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15, null=True, unique=True), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
