# Generated by Django 5.0 on 2024-07-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0013_delete_generalsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedWorkingdaysinamonth',
        ),
        migrations.DeleteModel(
            name='Latefineforfewdays',
        ),
        migrations.DeleteModel(
            name='Workingminutesperday',
        ),
    ]
