# Generated by Django 5.0 on 2024-07-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0017_consecutivelateattendancetofine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consecutivelateattendancetofine',
            new_name='Consecutivelateattendance',
        ),
    ]
