# Generated by Django 5.0 on 2024-07-02 09:48

import django.core.validators
import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0020_halfdaysalarydeduction_and_more'),
        ('leave', '0005_remove_leavesummary_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fiscalyear_month', models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=20)),
                ('workingday_starts_at', models.TimeField()),
                ('holiday_as_workingday', models.BooleanField(default=False)),
                ('consecutive_days_late_attendance_to_fine', models.IntegerField(default=3)),
                ('consecutive_late_attendance_to_fine', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fraction_of_daily_salary_for_halfday', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_working_hours_against_timesheet', models.FloatField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('consider_attendance_on_holidays', models.CharField(choices=[('Disabled', 'Disabled'), ('Overtime', 'Overtime')], max_length=15)),
                ('allow_overtime', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Consecutivelateattendance',
        ),
        migrations.DeleteModel(
            name='Fiscalyear',
        ),
        migrations.DeleteModel(
            name='Halfdaysalary',
        ),
        migrations.DeleteModel(
            name='Halfdaysalarydeduction',
        ),
        migrations.DeleteModel(
            name='Holidaysasworkingdays',
        ),
        migrations.DeleteModel(
            name='Maxworkinghoursagainsttimesheet',
        ),
        migrations.DeleteModel(
            name='Workingdaystartsat',
        ),
    ]
