# Generated by Django 5.0 on 2024-07-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0023_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyholiday',
            name='days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.weekdays'),
        ),
    ]
