# Generated by Django 5.0 on 2024-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0024_weeklyholiday_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyholiday',
            name='day',
        ),
    ]
