# Generated by Django 5.0 on 2024-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0025_remove_weeklyholiday_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyholiday',
            old_name='days',
            new_name='day',
        ),
    ]
