# Generated by Django 5.0 on 2024-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0027_generalsettings_weekly_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyholiday',
            name='day',
        ),
        migrations.AddField(
            model_name='weeklyholiday',
            name='day',
            field=models.ManyToManyField(blank=True, to='hrm_settings.weekdays'),
        ),
    ]
