# Generated by Django 5.0 on 2024-07-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0028_remove_weeklyholiday_day_weeklyholiday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='weekly_holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_settings.weeklyholiday'),
        ),
    ]
