# Generated by Django 5.0 on 2024-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_settings', '0029_alter_generalsettings_weekly_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, unique=True),
        ),
    ]
