# Generated by Django 5.0 on 2024-08-18 05:07

import django.core.validators
import helps.abstract.abstractclass
import jobrecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeejobhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('increment_on', models.CharField(blank=True, choices=[('Gross Salary', 'Gross Salary'), ('Basic Salary', 'Basic Salary')], max_length=50, null=True)),
                ('salary', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('increment_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('employee_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status_adjustment', models.CharField(blank=True, choices=[('Joining', 'Joining'), ('Increment', 'Increment'), ('Promotion', 'Promotion'), ('Demotion', 'Demotion'), ('Transfer', 'Transfer'), ('Terminated', 'Terminated')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=jobrecord.models.uploadjobhistory)),
                ('next_id', models.IntegerField(blank=True, null=True)),
                ('previous_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
