# Generated by Django 5.0 on 2024-08-25 08:20

import django.contrib.postgres.fields
import django.core.validators
import helps.abstract.abstractclass
import jobrecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeejobhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('increment_on', models.CharField(blank=True, choices=[('Gross Salary', 'Gross Salary'), ('Basic Salary', 'Basic Salary')], max_length=50, null=True)),
                ('salary', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('increment_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('employee_type', models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Intern', 'Intern'), ('Probation', 'Probation'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contractual', 'Contractual'), ('Comission', 'Comission'), ('Labour', 'Labour')], max_length=30, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status_adjustment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Joining', 'Joining'), ('Promotion', 'Promotion'), ('Increment', 'Increment'), ('Transfer', 'Transfer'), ('Status Update', 'Status Update'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=50), blank=True, null=True, size=None)),
                ('comment', models.TextField(blank=True, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=jobrecord.models.upload_jobhistory_files)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
