# Generated by Django 5.0 on 2024-08-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0003_initial'),
        ('company', '0002_initial'),
        ('department', '0002_initial'),
        ('jobrecord', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='appraisal_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_appraisal_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_department', to='department.department'),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_designation', to='user.designation'),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeejobhistory_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
