# Generated by Django 5.0 on 2024-08-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='job_status',
            field=models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=30, null=True),
        ),
    ]
