# Generated by Django 5.0 on 2024-08-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0002_rename_prev_employee_typr_employeejobhistory_prev_employee_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='appraisal_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_appraisal_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeejobhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeejobhistory_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
