# Generated by Django 5.0 on 2024-08-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_user'),
        ('company', '0011_basicinformation_industry_type'),
        ('department', '0002_initial'),
        ('jobrecord', '0003_alter_employeejobhistory_appraisal_by_and_more'),
        ('user', '0019_delete_salaryallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='prev_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_branch', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='employeejobhistory',
            name='prev_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employeejobhistory',
            name='prev_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_department', to='department.department'),
        ),
        migrations.AlterField(
            model_name='employeejobhistory',
            name='prev_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_designation', to='user.designation'),
        ),
    ]
