# Generated by Django 5.0 on 2024-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0003_remove_employeejobhistory_employee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Intern', 'Intern'), ('Probation', 'Probation'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contractual', 'Contractual'), ('Comission', 'Comission'), ('Labour', 'Labour')], max_length=30, null=True),
        ),
    ]
