# Generated by Django 5.0 on 2024-08-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0004_employeejobhistory_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='status_adjustment',
        ),
    ]
