# Generated by Django 5.0 on 2024-08-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0004_alter_employeejobhistory_prev_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='prev_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='prev_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='new_salary',
            new_name='current_salary',
        ),
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='prev_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='prev_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='prev_employee_type',
            new_name='employee_type',
        ),
    ]
