# Generated by Django 5.0 on 2024-08-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0005_rename_prev_branch_employeejobhistory_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='current_salary',
            new_name='new_salary',
        ),
    ]
