# Generated by Django 5.0 on 2024-08-20 06:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0005_remove_employeejobhistory_status_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='status_adjustment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Joining', 'Joining'), ('Increment', 'Increment'), ('Promotion', 'Promotion'), ('Demotion', 'Demotion'), ('Transfer', 'Transfer'), ('Terminated', 'Terminated')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
