# Generated by Django 5.0 on 2024-08-20 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0006_employeejobhistory_status_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
