# Generated by Django 5.0 on 2024-08-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0006_rename_current_salary_employeejobhistory_new_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='new_salary',
            new_name='salary',
        ),
    ]
