# Generated by Django 5.0 on 2024-08-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0007_alter_employeejobhistory_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
