# Generated by Django 5.0 on 2024-08-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0007_rename_new_salary_employeejobhistory_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='prev_salary',
        ),
    ]
