# Generated by Django 5.0 on 2024-08-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0008_remove_employeejobhistory_prev_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejobhistory',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='to_date',
        ),
    ]
