# Generated by Django 5.0 on 2024-08-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0008_alter_employeejobhistory_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='date',
        ),
    ]
