# Generated by Django 5.0 on 2024-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0009_rename_from_date_employeejobhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='next_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
