# Generated by Django 5.0 on 2024-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0009_remove_employeejobhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
