# Generated by Django 5.0 on 2024-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0010_employeejobhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
