# Generated by Django 5.0 on 2024-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0010_employeejobhistory_next_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='previous_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
