# Generated by Django 5.0 on 2024-08-21 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0012_alter_employeejobhistory_status_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobhistory',
            name='status_adjustment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Joining', 'Joining'), ('Promotion', 'Promotion'), ('Increment', 'Increment'), ('Transfer', 'Transfer'), ('Status Update', 'Status Update'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
