# Generated by Django 5.0 on 2024-08-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0013_alter_employeejobhistory_status_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='next_id',
        ),
        migrations.RemoveField(
            model_name='employeejobhistory',
            name='previous_id',
        ),
    ]
