# Generated by Django 5.0 on 2024-08-22 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecord', '0014_remove_employeejobhistory_next_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='next_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_next', to='jobrecord.employeejobhistory'),
        ),
        migrations.AddField(
            model_name='employeejobhistory',
            name='previous_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeejobhistory_previous', to='jobrecord.employeejobhistory'),
        ),
    ]
