apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: api-hrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: princeay0n/django-backend:latest
          env:
            - name: DATABASE_URL
              value: "postgres://root:API@2024#ltd@postgres-service:5432/api_hrm"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
  namespace: api-hrm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-backend
