# Generated by Django 5.0 on 2024-07-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialoffday', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offday',
        ),
    ]
