# Generated by Django 5.0 on 2024-06-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(default='admin1234', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
