# Generated by Django 5.0 on 2024-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_password_alter_device_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
