# Generated by Django 5.0 on 2024-07-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_group'),
        ('user', '0002_delete_groupofdevicegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devicegroup',
        ),
    ]
