# Generated by Django 5.0 on 2024-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicegroup_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='devicegroup',
            constraint=models.UniqueConstraint(fields=('group', 'device'), name='group_device'),
        ),
    ]
