# Generated by Django 5.0 on 2024-07-04 11:43

import django.db.models.deletion
import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_delete_devicegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
