# Generated by Django 5.0 on 2024-06-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldeduction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolldeductiontwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldeduction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolldeductionone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldeductionassign',
            name='payrolldeduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrolldeduction'),
        ),
        migrations.AddField(
            model_name='payrolldeductionassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollearning',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrollearningtwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollearning',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrollearningone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollearningassign',
            name='payrollearning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollearning'),
        ),
        migrations.AddField(
            model_name='payrollearningassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolltax',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolltaxtwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolltax',
            name='ethnicgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ethnicgroup'),
        ),
        migrations.AddField(
            model_name='payrolltax',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolltaxone', to=settings.AUTH_USER_MODEL),
        ),
    ]
