# Generated by Django 5.0 on 2024-05-30 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Fixed Amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollearning',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrollearning',
            name='amount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Fixed Amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollearning',
            name='depends_on_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payrolltax',
            name='max_income',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrolltax',
            name='min_income',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrolltax',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='payrolltax',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
