# Generated by Django 5.0 on 2024-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldeduction',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollearning',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
