# Generated by Django 5.0 on 2024-08-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        ('company', '0002_initial'),
        ('department', '0002_initial'),
        ('notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticeboard_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticeboard_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeboardbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardbranch_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='noticeboardbranch',
            name='noticeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardbranch_noticeboard', to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboardcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardcompany_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='noticeboardcompany',
            name='noticeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardcompany_noticeboard', to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboarddepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboarddepartment_department', to='department.department'),
        ),
        migrations.AddField(
            model_name='noticeboarddepartment',
            name='noticeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboarddepartment_noticeboard', to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboardemployee',
            name='noticeboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardemployee_noticeboard', to='notice.noticeboard'),
        ),
        migrations.AddField(
            model_name='noticeboardemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboardemployee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
