# Generated by Django 5.0 on 2024-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteboard',
            name='publish_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
