# Generated by Django 5.0 on 2024-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
