# Generated by Django 5.0 on 2024-08-25 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_initial'),
        ('company', '0002_initial'),
        ('department', '0002_initial'),
        ('notice', '0003_alter_noticeboard_publish_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='noticeboardbranch',
            constraint=models.UniqueConstraint(fields=('noticeboard', 'branch'), name='notice_branch'),
        ),
        migrations.AddConstraint(
            model_name='noticeboardcompany',
            constraint=models.UniqueConstraint(fields=('noticeboard', 'company'), name='notice_company'),
        ),
        migrations.AddConstraint(
            model_name='noticeboarddepartment',
            constraint=models.UniqueConstraint(fields=('noticeboard', 'department'), name='notice_department'),
        ),
        migrations.AddConstraint(
            model_name='noticeboardemployee',
            constraint=models.UniqueConstraint(fields=('noticeboard', 'user'), name='notice_user'),
        ),
    ]
