# Generated by Django 5.0 on 2024-06-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinformation',
            old_name='cupdated_by',
            new_name='updated_by',
        ),
    ]
