# Generated by Django 5.0 on 2024-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
