# Generated by Django 5.0 on 2024-08-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='basic_information',
        ),
    ]
