# Generated by Django 5.0 on 2024-07-08 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companytype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='companyone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_owner',
            field=models.ManyToManyField(blank=True, related_name='companytwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
