# Generated by Django 5.0 on 2024-08-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_basic_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='basic_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.basicinformation'),
        ),
    ]
