# Generated by Django 5.0 on 2024-08-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_basic_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='basic_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.basicinformation'),
        ),
    ]
