# Generated by Django 5.0 on 2024-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_user_alter_company_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
