# Generated by Django 5.0 on 2024-08-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_basic_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='basic_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.basicinformation'),
        ),
    ]
