# Generated by Django 5.0 on 2024-07-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companytype',
            name='updated_by',
        ),
    ]
