# Generated by Django 5.0 on 2024-07-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_companytype_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updatecompanytype',
        ),
        migrations.DeleteModel(
            name='Updatecompanytypeconfig',
        ),
    ]
