# Generated by Django 5.0 on 2024-07-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_delete_updatecompanytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
