# Generated by Django 5.0 on 2024-07-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='industry_type',
        ),
        migrations.DeleteModel(
            name='Companytype',
        ),
    ]
