# Generated by Django 5.0 on 2024-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_basicinformation_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='industry_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
