# Generated by Django 5.0 on 2024-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_no',
            field=models.CharField(max_length=50),
        ),
    ]
