# Generated by Django 5.0 on 2024-05-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='address',
        ),
    ]
