# Generated by Django 5.0 on 2024-05-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_remove_bankaccount_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contribution.address'),
        ),
    ]
