# Generated by Django 5.0 on 2024-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_alter_bankaccount_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
