# Generated by Django 5.0 on 2024-08-24 08:00

import helps.validators.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[helps.validators.common.validate_phone_number]),
        ),
    ]
