# Generated by Django 5.0 on 2024-05-19 06:18

import django.core.validators
import django.db.models.deletion
import helps.abstract.abstractclass
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Employeeacademichistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('board_institute_name', models.CharField(max_length=150)),
                ('certification', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=50)),
                ('score_grade', models.CharField(max_length=4)),
                ('year_of_passing', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employeedocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=user.models.uploaddocs)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employeeexperiencehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employeeincrementrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('increment_on', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('new_salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('increment_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bank_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cash_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(blank=True, choices=[('Joining', 'Joining'), ('Increment', 'Increment'), ('Promotion', 'Promotion')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
