# Generated by Django 5.0 on 2024-07-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupofdevicegroup',
        ),
    ]
