# Generated by Django 5.0 on 2024-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
    ]
