# Generated by Django 5.0 on 2024-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='required_skill',
            field=models.ManyToManyField(blank=True, to='user.requiredskill'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='responsibility',
            field=models.ManyToManyField(blank=True, to='user.responsibility'),
        ),
    ]
