# Generated by Django 5.0 on 2024-07-07 11:15

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_groupofdevicegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(blank=True, default=user.models.generate_unique_code, max_length=18, null=True),
        ),
    ]
