# Generated by Django 5.0 on 2024-06-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_designation_required_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.grade'),
        ),
    ]
