# Generated by Django 5.0 on 2024-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employeecontact_name_employeeacademichistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated ', 'Separated')], default='Single', max_length=20),
        ),
    ]
