# Generated by Django 5.0 on 2024-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_status',
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated ', 'Separated')], max_length=20, null=True),
        ),
    ]
