# Generated by Django 5.0 on 2024-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
