# Generated by Django 5.0 on 2024-07-07 11:16

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(default=user.models.generate_unique_code, max_length=18),
        ),
    ]
