# Generated by Django 5.0 on 2024-08-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicegroup_title'),
        ('user', '0003_remove_userdevicegroup_user_devicegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevicegroup',
            name='devicegroup',
        ),
        migrations.AddField(
            model_name='userdevicegroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='device.group'),
        ),
    ]
