# Generated by Django 5.0 on 2024-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_designation_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hr_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
