# Generated by Django 5.0 on 2024-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_job_status_user_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_status',
            field=models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], max_length=30, null=True),
        ),
    ]
