# Generated by Django 5.0 on 2024-08-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicegroup_title'),
        ('user', '0004_remove_userdevicegroup_devicegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevicegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='device.group'),
        ),
    ]
