# Generated by Django 5.0 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_shift_created_by_alter_shift_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdaysalary',
            name='calculation_based_on',
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Paymentrecord',
        ),
        migrations.DeleteModel(
            name='Perdaysalary',
        ),
    ]
