# Generated by Django 5.0 on 2024-05-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='updated_by',
        ),
    ]
