# Generated by Django 5.0 on 2024-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_hr_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hr_password',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
