# Generated by Django 5.0 on 2024-08-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicegroup_title'),
        ('user', '0005_alter_userdevicegroup_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdevicegroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='user_group'),
        ),
    ]
