# Generated by Django 5.0 on 2024-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_shift_created_by_remove_shift_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
