# Generated by Django 5.0 on 2024-09-05 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdevicegroup_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='early_leave_tolerance_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
