# Generated by Django 5.0 on 2024-05-21 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_dummy_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dummy_salary',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='gross_salary',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
