# Generated by Django 5.0 on 2024-05-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_shift_created_by_shift_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftchangerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shiftchangerequest',
            name='updated_by',
        ),
    ]
