# Generated by Django 5.0 on 2024-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_active_dummy_salary_user_dummy_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
