# Generated by Django 5.0 on 2024-07-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bonus_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='July', max_length=20),
        ),
    ]
