# Generated by Django 5.0 on 2024-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocs',
            name='attachment',
        ),
    ]
