# Generated by Django 5.0 on 2024-05-29 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_shiftchangerequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftchangerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shiftchangerequestfour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shiftchangerequestthree', to=settings.AUTH_USER_MODEL),
        ),
    ]
