# Generated by Django 5.0 on 2024-05-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_shiftchangerequest_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftchangerequest',
            name='created_by',
        ),
    ]
