# Generated by Django 5.0 on 2024-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_payment_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontact',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
