# Generated by Django 5.0 on 2024-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_late_tolerance_time_shift_late_in_tolerance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_status',
            field=models.CharField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired'), ('Expired', 'Expired')], max_length=30, null=True),
        ),
    ]
