# Generated by Django 5.0 on 2024-07-07 11:38

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_employeedocs_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocs',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=user.models.uploaddocs),
        ),
    ]
