# Generated by Django 5.0 on 2024-05-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_phone_employeecontact_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_permission',
        ),
    ]
