# Generated by Django 5.0 on 2024-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_employeedocs_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_in',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank')], max_length=50, null=True),
        ),
    ]
