# Generated by Django 5.0 on 2024-07-15 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_payment_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='besic_salary',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
