# Generated by Django 5.0 on 2024-05-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_role_user_role_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Rolepermission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_permission',
        ),
    ]
