# Generated by Django 5.0 on 2024-07-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_besic_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employeeincrementrecord',
        ),
    ]
