# Generated by Django 5.0 on 2024-07-18 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_employeeincrementrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
