# Generated by Django 5.0 on 2024-07-18 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_employeecontact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeacademichistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_academichistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedocs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeexperiencehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_experiencehistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
