# Generated by Django 5.0 on 2024-08-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobilenumber',
        ),
    ]
