# Generated by Django 5.0 on 2024-08-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_mobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salaryallocation',
        ),
    ]
