# Generated by Django 5.0 on 2024-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_salaryallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Intern', 'Intern'), ('Probation', 'Probation'), ('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contractual', 'Contractual'), ('Comission', 'Comission'), ('Labour', 'Labour')], max_length=30, null=True),
        ),
    ]
