# Generated by Django 5.0 on 2024-08-10 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicgroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='ethnicgroup_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
