# Generated by Django 5.0 on 2024-08-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_note_created_by_alter_note_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='besic_salary',
            new_name='basic_salary',
        ),
    ]
