# Generated by Django 5.0 on 2024-08-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_besic_salary_user_basic_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basic_salary',
        ),
    ]
