# Generated by Django 5.0 on 2024-06-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('company', '0001_initial'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchone', to='company.company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='facilities',
            field=models.ManyToManyField(to='facility.facility'),
        ),
        migrations.AddField(
            model_name='branchemail',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchphonenumber',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
