# Generated by Django 5.0 on 2024-08-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_company', to='company.company'),
        ),
        migrations.AddConstraint(
            model_name='operatinghour',
            constraint=models.UniqueConstraint(fields=('operating_hour_from', 'operating_hour_to'), name='Operatinghour_operating_hour_from_operating_hour_to'),
        ),
    ]
