# Generated by Django 5.0 on 2024-06-03 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='operatinghour',
            constraint=models.UniqueConstraint(fields=('operating_hour_from', 'operating_hour_to'), name='Operatinghour_operating_hour_from_operating_hour_to'),
        ),
        migrations.AddField(
            model_name='branch',
            name='operating_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.operatinghour'),
        ),
    ]
