# Generated by Django 5.0 on 2024-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operatinghour',
            constraint=models.UniqueConstraint(fields=('operating_hour_from', 'operating_hour_to'), name='Operatinghour_operating_hour_from_operating_hour_to'),
        ),
    ]
