# Generated by Django 5.0 on 2024-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_initial'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='facility.facility'),
        ),
    ]
