# Generated by Django 5.0 on 2024-08-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_initial'),
        ('company', '0005_alter_company_basic_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_company', to='company.company'),
        ),
    ]
