# Generated by Django 5.0 on 2024-07-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_branch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
    ]
