# Generated by Django 5.0 on 2024-06-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='operating_hour',
        ),
    ]
