# Generated by Django 5.0 on 2024-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
