# Generated by Django 5.0 on 2024-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
