# Generated by Django 5.0 on 2024-05-26 03:12

import django.contrib.postgres.fields
import django.core.validators
import helps.abstract.abstractclass
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('in_negative_minutes', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_positive_minutes', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('out_negative_minutes', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('out_positive_minutes', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('late_in_based_on_buffertime', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('early_leave_based_on_buffertime', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_minutes', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_out_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), blank=True, null=True, size=None)),
                ('buffer_time_minutes', models.CharField(blank=True, max_length=25, null=True)),
                ('attendance_from', models.CharField(choices=[('Device', 'Device'), ('Manual', 'Manual'), ('Remote', 'Remote')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Devicelogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Remotelogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requestmanualattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('admin_note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requestremoteattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=helps.abstract.abstractclass.generate_unique_code, editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('in_out_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
