# Generated by Django 5.0 on 2024-07-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='office_off_day',
        ),
    ]
