# Generated by Django 5.0 on 2024-07-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('leave', '0004_alter_leavesummary_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.holiday'),
        ),
    ]
