# Generated by Django 5.0 on 2024-05-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_approved_by_requestmanualattendance_decisioned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestremoteattendance',
            old_name='approved_by',
            new_name='decisioned_by',
        ),
    ]
