# Generated by Django 5.0 on 2024-09-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_working_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='early_leave_based_on_buffertime',
        ),
    ]
