# Generated by Django 5.0 on 2024-07-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_office_off_day'),
        ('hrm_settings', '0009_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='office_off_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm_settings.holiday'),
        ),
    ]
