# Generated by Django 5.0 on 2024-09-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_early_leave_based_on_buffertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='late_in_based_on_buffertime',
            new_name='late_based_on_buffertime',
        ),
    ]
