# Generated by Django 5.0 on 2024-09-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_late_in_based_on_buffertime_attendance_late_based_on_buffertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='buffer_time_minutes',
        ),
    ]
