# Generated by Django 5.0 on 2024-09-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_buffer_time_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='holiday',
        ),
        migrations.CreateModel(
            name='Attendancestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Half Present', 'Half Present'), ('Late Attendance', 'Late Attendance'), ('Early Leave', 'Early Leave'), ('Overtime', 'Overtime'), ('Holiday', 'Holiday'), ('Incomplete', 'Incomplete')], max_length=15)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
            ],
        ),
    ]
