# Generated by Django 5.0 on 2024-09-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_holiday_attendancestatus'),
        ('department', '0002_initial'),
        ('user', '0007_shift_early_leave_tolerance_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='in_negative_minutes',
            new_name='early_leave_based_on_buffertime',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='in_positive_minutes',
            new_name='late_in_based_on_buffertime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_based_on_buffertime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='out_negative_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='out_positive_minutes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.designation'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.shift'),
        ),
    ]
