# Generated by Django 5.0 on 2024-09-05 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_in_negative_minutes_attendance_early_leave_based_on_buffertime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_from',
            new_name='attendance_mode',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='early_leave_based_on_buffertime',
            new_name='early_leave',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='late_in_based_on_buffertime',
            new_name='late_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='in_out_times',
        ),
        migrations.AddField(
            model_name='attendance',
            name='over_time',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
