# Generated by Django 5.0 on 2024-08-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_company'),
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_branch', to='branch.branch'),
        ),
    ]
