# Generated by Django 5.0 on 2024-06-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
