# Generated by Django 5.0 on 2024-08-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
    ]
