# Generated by Django 5.0 on 2024-05-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
    ]
