# Generated by Django 5.0 on 2024-06-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
        ('department', '0003_remove_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contribution.address'),
        ),
        migrations.AddField(
            model_name='department',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
