# Generated by Django 5.0 on 2024-06-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_alter_branch_fax'),
        ('department', '0004_department_address_department_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
