# Generated by Django 5.0 on 2024-08-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_user'),
        ('department', '0004_department_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
