# Generated by Django 5.0 on 2024-05-21 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_department_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(related_name='departmenttwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ManyToManyField(related_name='departmentone', to=settings.AUTH_USER_MODEL),
        ),
    ]
